### ISSUE TITLE
Not able to connect to Neptue using java error :  java.lang.RuntimeException: java.lang.RuntimeException: org.apache.tinkerpop.gremlin.driver.exception.NoHostAvailableException: All hosts are considered unavailable due to previous exceptions. Check the error log to find the actual reason. 	at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.promise(RemoteStep.java:98)

### ISSUE THREAD

**Issue by jrkmhl** [aws/amazon-neptune-gremlin-java-sigv4#41]
If i enable iam authentication to neptune , its timing out with exception .
I followed the https://github.com/aws/amazon-neptune-gremlin-java-sigv4/blob/master/src/main/java/com/amazon/neptune/gremlin/driver/example/NeptuneGremlinSigV4Example.java same example

Here is the full log

Successfully loaded SigV4 properties from provider:
Exception in thread "main" java.lang.IllegalStateException: org.apache.tinkerpop.gremlin.process.remote.RemoteConnectionException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.tinkerpop.gremlin.driver.exception.NoHostAvailableException: All hosts are considered unavailable due to previous exceptions. Check the error log to find the actual reason.
	at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.promise(RemoteStep.java:98)
	at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.processNextStart(RemoteStep.java:65)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:144)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:196)
	at com.amazon.neptune.gremlin.driver.example.NeptuneGremlinSigV4Example.main(NeptuneGremlinSigV4Example.java:104)
Caused by: org.apache.tinkerpop.gremlin.process.remote.RemoteConnectionException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.tinkerpop.gremlin.driver.exception.NoHostAvailableException: All hosts are considered unavailable due to previous exceptions. Check the error log to find the actual reason.
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection.submitAsync(DriverRemoteConnection.java:227)
	at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.promise(RemoteStep.java:89)
	... 4 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.tinkerpop.gremlin.driver.exception.NoHostAvailableException: All hosts are considered unavailable due to previous exceptions. Check the error log to find the actual reason.
	at org.apache.tinkerpop.gremlin.driver.Client$AliasClusteredClient.submitAsync(Client.java:598)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection.submitAsync(DriverRemoteConnection.java:225)
	... 5 more
Caused by: java.lang.RuntimeException: org.apache.tinkerpop.gremlin.driver.exception.NoHostAvailableException: All hosts are considered unavailable due to previous exceptions. Check the error log to find the actual reason.
	at org.apache.tinkerpop.gremlin.driver.Client.submitAsync(Client.java:382)
	at org.apache.tinkerpop.gremlin.driver.Client$AliasClusteredClient.submitAsync(Client.java:616)
	at org.apache.tinkerpop.gremlin.driver.Client$AliasClusteredClient.submitAsync(Client.java:596)
	... 6 more
Caused by: org.apache.tinkerpop.gremlin.driver.exception.NoHostAvailableException: All hosts are considered unavailable due to previous exceptions. Check the error log to find the actual reason.

**Comment by yigithub** [comment]
Hi, can you try curl from the same host and see if the neptune endpoint is reachable. It could be a reachability/SG/VPC issue..

Also, how are you providing the credentials and the SERVICE_REGION values to the runtime?  You can set up credentials through environment variable, or profile, or System property. SERVICE_REGION needs to be an environment variable.

**Comment by iowusu** [comment]
I am having similar issue. In my case I can curl to the Neptune successfully. 

I followed https://docs.aws.amazon.com/neptune/latest/userguide/iam-auth-connecting-gremlin-java.html
